fix(OnyxListbox): Fix hover colors on OnyxListbox and OnyxNavItem
SchwarzIT/onyx pull request #1019
Opened 2024-04-25 10:25 UTC by MajaZarkova

Relates to #874 

Fix hover colors on OnyxListbox and OnyxNavItem

## Checklist

- [ ] If a new component is added, at least one [Playwright screenshot test](https://github.com/SchwarzIT/onyx/actions/workflows/playwright-screenshots.yml) is added
- [ ] A changeset is added with `npx changeset add` if your changes should be released as npm package (because they affect the library usage)

2024-04-25 11:51 UTC, larsrickert requested changes

2024-04-25 11:51 UTC, larsrickert commented on packages/sit-onyx/playwright/snapshots/components/OnyxListboxOption/Listbox-option-default--webkit-linux.png
focus-visible should also have the colored font, right?

2024-04-26 10:35 UTC, larsrickert requested changes

2024-04-26 11:35 UTC, MajaZarkova commented on packages/sit-onyx/playwright/snapshots/components/OnyxListboxOption/Listbox-option-default--webkit-linux.png
Yes, I'm fighting with it. It's confusing.

2024-05-07 08:49 UTC, larsrickert approved these changes

2024-05-07 09:00 UTC, merged