Jlc/chore split listbox list
SchwarzIT/onyx pull request #1037
Opened 2024-05-03 15:23 UTC by JoCa96

Relates to #

## Checklist

- [ ] The added / edited code has been documented with [JSDoc](https://jsdoc.app/about-getting-started)
- [ ] All changes are documented in the documentation app (folder `apps/docs`)
- [ ] If a new component is added, at least one [Playwright screenshot test](https://github.com/SchwarzIT/onyx/actions/workflows/playwright-screenshots.yml) is added
- [ ] A changeset is added with `npx changeset add` if your changes should be released as npm package (because they affect the library usage)

2024-05-09 07:35 UTC, MajaZarkova requested changes

2024-05-09 07:35 UTC, MajaZarkova commented on packages/sit-onyx/src/components/OnyxFlyoutMenu/OnyxFlyoutMenu.stories.ts
> +  title: "support/OnyxFlyoutMenu",
```suggestion
  title: "support/FlyoutMenu",
```
We don't use the Onyx prefix here :)

2024-05-09 07:35 UTC, MajaZarkova commented on packages/sit-onyx/src/components/OnyxListbox/OnyxListbox.vue
The style for multiselect listbox is messed up
![image](https://github.com/SchwarzIT/onyx/assets/60856270/9c1d966e-55cb-459b-8915-01e5d7a1fdb8)

FIgma:
![image](https://github.com/SchwarzIT/onyx/assets/60856270/b4b0a350-f71d-41a4-bb4e-3436803df616)

2024-05-09 07:35 UTC, MajaZarkova commented on packages/sit-onyx/src/components/OnyxFlyoutMenu/OnyxFlyoutMenu.vue
Is it intentional that focus-visible and keyboard navigation is not supported?

2024-05-10 06:06 UTC, MajaZarkova commented on packages/sit-onyx/src/components/OnyxListbox/OnyxListbox.vue
I fixed this in another PR :)

2024-05-10 10:19 UTC, JoCa96 commented on packages/sit-onyx/src/components/OnyxFlyoutMenu/OnyxFlyoutMenu.stories.ts
> +  title: "support/OnyxFlyoutMenu",
fixed

2024-05-10 10:19 UTC, JoCa96 commented on packages/sit-onyx/src/components/OnyxFlyoutMenu/OnyxFlyoutMenu.vue
yes, thats part of #1047

2024-05-10 10:45 UTC, MajaZarkova submitted a review, later dismissed

2024-05-10 10:59 UTC, MajaZarkova requested changes

2024-05-10 10:59 UTC, MajaZarkova commented on packages/sit-onyx/src/components/OnyxListboxOption/OnyxListboxOption.vue
Density is broken

2024-05-10 11:58 UTC, JoCa96 commented on packages/sit-onyx/src/components/OnyxListboxOption/OnyxListboxOption.vue
fixed :)

2024-05-10 12:00 UTC, MajaZarkova approved these changes

2024-05-10 12:01 UTC, merged