fix(OnyxCheckbox,OnyxRadioButton,OnyxSwitch,OnyxSelect): reset control sizes to ignore density
SchwarzIT/onyx pull request #1207
Opened 2024-05-29 14:44 UTC by BoppLi

Relates to #1194

Reset control sizes to ignore density.
Fix RadioButton alignment to center with the label.

## Checklist

- [ ] The added / edited code has been documented with [JSDoc](https://jsdoc.app/about-getting-started)
- [ ] If a new component is added, at least one [Playwright screenshot test](https://github.com/SchwarzIT/onyx/actions/workflows/playwright-screenshots.yml) is added
- [ ] A changeset is added with `npx changeset add` if your changes should be released as npm package (because they affect the library usage)

2024-05-29 15:10 UTC, larsrickert requested changes
Still not a huge fan of the updates visuals because the densities can not really be differentiated any longer but ux decided like this so

2024-05-29 15:10 UTC, larsrickert commented on packages/sit-onyx/playwright/snapshots/components/OnyxRadioButton/Radio-button-truncation--chromium-linux.png
The radio button should be top aligned when multiline

2024-05-29 15:10 UTC, larsrickert commented on packages/sit-onyx/src/components/OnyxSwitch/OnyxSwitch.vue
> +      height: unset;
Why is this needed? Can't we just remove it?

2024-05-31 07:53 UTC, larsrickert commented on packages/sit-onyx/playwright/snapshots/components/OnyxRadioButton/Radio-button-truncation--chromium-linux.png
Hmm but I remember that I discussed this with Jannick and he told me the default should be top aligned but the project can override it to be centered...lets double check this with @jannick-ux

2024-06-03 07:30 UTC, BoppLi commented on packages/sit-onyx/playwright/snapshots/components/OnyxRadioButton/Radio-button-truncation--chromium-linux.png
ok I added it to the agenda of tomorrows discussion with jannick at 10:00

2024-06-04 08:18 UTC, BoppLi commented on packages/sit-onyx/playwright/snapshots/components/OnyxRadioButton/Radio-button-truncation--chromium-linux.png
Answer from UX: top aligned is default

2024-06-04 09:52 UTC, BoppLi commented on packages/sit-onyx/playwright/snapshots/components/OnyxCheckbox/Checkbox-other--chromium-linux.png
TODO optional got messed up

2024-06-04 09:56 UTC, BoppLi commented on packages/sit-onyx/playwright/snapshots/components/OnyxSwitch/Switch-hidden-label--chromium-linux.png
todo this matrix does not make any sense anymore?

2024-06-04 12:01 UTC, larsrickert approved these changes

2024-06-04 12:09 UTC, merged