chore(docs): Add imprint link to footer
SchwarzIT/onyx pull request #1351
Opened 2024-06-18 14:45 UTC by JoCa96

Relates to #1350 

Provided custom footer with the original vitepress style.
A custom footer was necessary, as it is shown on every page.
The default footer was not shown on pages where the side-bar was opened.

2024-06-18 14:54 UTC, larsrickert requested changes

2024-06-18 14:55 UTC, larsrickert commented on apps/docs/src/.vitepress/theme/TheLayout.vue
> +        <a class="footer__imprint" href="https://it.schwarz/impressum"> Imprint </a>
```suggestion
        <a class="footer__imprint" href="https://it.schwarz/impressum" target="_blank"> Imprint </a>
```

2024-06-18 15:12 UTC, JoCa96 commented on apps/docs/src/.vitepress/theme/TheLayout.vue
> +        <a class="footer__imprint" href="https://it.schwarz/impressum"> Imprint </a>
Imho it doesn't really match the theme of the footer:
<img width="328" alt="Screenshot 2024-06-18 at 17 12 13" src="https://github.com/SchwarzIT/onyx/assets/18483883/7227b9e5-1c51-4112-944a-4ee7ccc29e7f">

2024-06-18 15:14 UTC, JoCa96 commented on apps/docs/src/.vitepress/theme/TheLayout.vue
> +    line-height: 24px;
I took over the stylings from the original footer. I would prefer to keep them as `px`, so that it behaves the same.

2024-06-19 06:44 UTC, BoppLi approved these changes
storybook does not need the imprint, right?

2024-06-19 06:49 UTC, JoCa96 commented
> storybook does not need the imprint, right?

That's a very good question, I think we probably need to.

2024-06-19 06:55 UTC, merged