[DRAFT] fix(OnyxNavBar): truncate app area and mobile page name
SchwarzIT/onyx pull request #1540
Opened 2024-07-10 07:10 UTC by larsrickert

Relates to #

## Checklist

- [ ] The added / edited code has been documented with [JSDoc](https://jsdoc.app/about-getting-started)
- [ ] All changes are documented in the documentation app (folder `apps/docs`)
- [ ] If a new component is added, at least one [Playwright screenshot test](https://github.com/SchwarzIT/onyx/actions/workflows/playwright-screenshots.yml) is added
- [ ] A changeset is added with `npx changeset add` if your changes should be released as npm package (because they affect the library usage)

2024-07-11 14:09 UTC, BoppLi submitted a review, later dismissed

2024-07-11 14:25 UTC, larsrickert commented on packages/sit-onyx/playwright/snapshots/components/OnyxNavBar/truncated-app-name-chromium-linux.png
Can you also include the context area so that we ensure that it is not pushed away?
Same for the mobile page title example :)

2024-07-11 14:26 UTC, BoppLi commented on packages/sit-onyx/playwright/snapshots/components/OnyxNavBar/truncated-app-name-chromium-linux.png
good idea, thx!

2024-07-11 15:16 UTC, BoppLi approved these changes

2024-07-12 06:47 UTC, MajaZarkova requested changes
When I run the branch I get these errors

![image](https://github.com/user-attachments/assets/88ecbe14-bc3c-486a-848b-0db88d6c5ff5)


Is it happening only on my machine?

2024-07-12 06:58 UTC, larsrickert commented
> When I run the branch I get these errors

No I think this is a SCSS warning due to a recent dependency update that deprecates a feature we are using :)
We can update this in a follow up PR, it should not break something for now

2024-07-12 07:10 UTC, MajaZarkova approved these changes

2024-07-12 07:19 UTC, merged