fix(OnyxNavButton): prevent parent highlighting when an active child is visible on mobile
SchwarzIT/onyx pull request #1559
Opened 2024-07-12 11:18 UTC by BoppLi

Closes #1483

When a nav button on the mobile menu is opened to show it's children and one of the children is active, the nav button should not be highlighted. The nav button should only be highlighted when it itself is active or when it's children are not displayed (when the menu was just opened).

## Checklist

- [x] The added / edited code has been documented with [JSDoc](https://jsdoc.app/about-getting-started)
- [x] If a new component is added, at least one [Playwright screenshot test](https://github.com/SchwarzIT/onyx/actions/workflows/playwright-screenshots.yml) is added
- [x] A changeset is added with `npx changeset add` if your changes should be released as npm package (because they affect the library usage)

2024-07-12 11:50 UTC, MajaZarkova requested changes

2024-07-12 11:50 UTC, MajaZarkova commented on packages/sit-onyx/playwright/snapshots/components/OnyxNavBar/modules/OnyxNavButton/NavButton-mobile-open-children--webkit-linux.png
Isn't the default parent still active?

2024-07-12 11:58 UTC, BoppLi commented on packages/sit-onyx/playwright/snapshots/components/OnyxNavBar/modules/OnyxNavButton/NavButton-mobile-open-children--webkit-linux.png
what's up with webkit :O it seems that it is hovered, but not on firefox and chromium..

2024-07-12 12:31 UTC, BoppLi commented on packages/sit-onyx/playwright/snapshots/components/OnyxNavBar/modules/OnyxNavButton/NavButton-mobile-open-children--webkit-linux.png
solved :)

2024-07-22 07:02 UTC, MajaZarkova approved these changes

2024-07-22 07:12 UTC, merged