fix(OnyxStepper): Remove default model value and placeholder for onyx stepper
SchwarzIT/onyx pull request #1619
Opened 2024-07-24 11:51 UTC by MajaZarkova

Relates to #1608 

Remove default model value and placeholder for onyx stepper

## Checklist

- [ ] The added / edited code has been documented with [JSDoc](https://jsdoc.app/about-getting-started)
- [ ] All changes are documented in the documentation app (folder `apps/docs`)
- [ ] If a new component is added, at least one [Playwright screenshot test](https://github.com/SchwarzIT/onyx/actions/workflows/playwright-screenshots.yml) is added
- [ ] A changeset is added with `npx changeset add` if your changes should be released as npm package (because they affect the library usage)

2024-07-24 11:58 UTC, larsrickert requested changes

2024-07-24 11:58 UTC, larsrickert commented on packages/sit-onyx/src/components/OnyxStepper/OnyxStepper.vue
> +  "update:modelValue": [value: number | undefined];
```suggestion
  "update:modelValue": [value?: number];
```

2024-07-25 05:54 UTC, BoppLi approved these changes

2024-07-25 06:52 UTC, JoCa96 requested changes

2024-07-25 06:52 UTC, JoCa96 commented on packages/sit-onyx/playwright/snapshots/components/OnyxStepper/Stepper-labelTooltip-messageTooltip--webkit-linux.png
Without a default value, it looks too empty. Can we keep `0` as a default value?

2024-07-25 06:59 UTC, larsrickert approved these changes

2024-07-25 07:27 UTC, JoCa96 commented
As discussed, please only emit in the `computed`. In the `handleClick` check for NaN and emit `undefined`.

2024-07-25 07:28 UTC, JoCa96 requested changes
As discussed, please only emit in the `computed`. In the `handleClick` check for NaN and emit `undefined`.

2024-07-25 09:19 UTC, JoCa96 approved these changes

2024-07-25 10:00 UTC, merged