feat(OnyxSelect): Implement OnyxSelect open direction and alignment
SchwarzIT/onyx pull request #1745
Opened 2024-08-14 08:43 UTC by MajaZarkova

Relates to #1198 

Added new feature which is calculating the space above and below the component and based on that the flyout will open to the top or bottom. I also added new 'alignment' property which will align the flyout to the right, left or will set the width to match the width of the input.

## Checklist

- [x] The added / edited code has been documented with [JSDoc](https://jsdoc.app/about-getting-started)
- [ ] If a new component is added, at least one [Playwright screenshot test](https://github.com/SchwarzIT/onyx/actions/workflows/playwright-screenshots.yml) is added
- [ ] A changeset is added with `npx changeset add` if your changes should be released as npm package (because they affect the library usage)

2024-08-16 07:37 UTC, larsrickert requested changes

2024-08-16 07:37 UTC, larsrickert commented on .changeset/ten-scissors-boil.md
> +Added new feature which is calculating the space above and below the component and based on that the flyout will open to the top or bottom. I also added new 'alignment' property which will align the
feat(OnyxSelect): add property `alignment` and auto detection for opening to top/bottom depending on the available space

2024-08-16 08:16 UTC, MajaZarkova commented on packages/sit-onyx/src/styles/mixins/list.scss
> +  // max-width: 20rem;
I set the max-width when left/right is used and I will clarify with Jannick about full width

2024-08-16 09:13 UTC, MajaZarkova commented on packages/sit-onyx/playwright/snapshots/components/OnyxSelect/Select-loading--chromium-linux.png
I checked Storybook and it's hovered there as well 

<img width="430" alt="image" src="https://github.com/user-attachments/assets/732f252b-ff85-402c-bfb2-cf252c0fd333">

Did we change something in the button?

2024-08-16 09:15 UTC, MajaZarkova commented on packages/sit-onyx/playwright/snapshots/components/OnyxSelect/Select-loading--chromium-linux.png
There is --onyx-color-base-background-tinted applied to the button

2024-08-16 09:19 UTC, MajaZarkova commented on packages/sit-onyx/playwright/snapshots/components/OnyxSelect/Select-loading--chromium-linux.png
https://github.com/SchwarzIT/onyx/pull/1609/files

2024-08-16 09:20 UTC, MajaZarkova commented on packages/sit-onyx/playwright/snapshots/components/OnyxSelect/Select-loading--chromium-linux.png
Here we changed the color of the button

2024-08-16 11:59 UTC, MajaZarkova commented on packages/sit-onyx/src/components/OnyxSelect/OnyxSelect.vue
> +const openDirection = ref<"top" | "bottom">();
This is handled by the new composable now

2024-08-16 11:59 UTC, MajaZarkova commented on packages/sit-onyx/src/components/OnyxSelect/OnyxSelect.vue
> +  detectOpenDirection();
This is handled by the composable

2024-08-16 13:41 UTC, larsrickert commented on packages/sit-onyx/playwright/snapshots/components/OnyxSelect/Select-loading--chromium-linux.png
Ups, thats not intentional then and a bug...

2024-08-16 13:43 UTC, larsrickert requested changes

2024-08-16 13:43 UTC, larsrickert commented on packages/sit-onyx/src/styles/mixins/list.scss
Removing the max width here would also remove it for all other flyouts like nav item, user menu etc...I think its better if we leave it here and override/unset it only in the select if full width is used

2024-08-19 07:47 UTC, MajaZarkova commented on packages/sit-onyx/playwright/snapshots/components/OnyxSelect/Select-loading--chromium-linux.png
Follow up ticket -> #1764

2024-08-21 07:04 UTC, larsrickert approved these changes

2024-08-21 07:33 UTC, merged