Feat/730 auto alignment tooltip
SchwarzIT/onyx pull request #1821
Opened 2024-09-02 13:41 UTC by ChristianBusshoff

- add auto alingment to the tooltip component
- add screenshot-tests
- add a demo on the homeView

2024-09-03 06:17 UTC, BoppLi commented
please adjust the PR title to the convention :)
`feat(OnyxTooltip): auto align tooltip`

the pattern is 
- feat/fix/chore
- optional scope/component name in brackets
- a short sentence describing the change, starting with an imperative verb :)

2024-09-03 06:18 UTC, BoppLi commented on apps/demo-app/src/views/HomeView.vue
> +          :style="{
please move styles to a class

2024-09-03 06:20 UTC, BoppLi commented on apps/demo-app/src/views/HomeView.vue
> +        </div>
- please move styles to a class
- if you bundle the examples, you can set v-if just once on the div :)
```suggestion
        <div class="tooltip-demo" v-if="show('OnyxTooltip')" >
          <OnyxTooltip text="Example tooltip text">
            <template #default="{ trigger }">
              <OnyxButton label="Left" v-bind="trigger" />
            </template>
          </OnyxTooltip>
          <OnyxTooltip text="Example tooltip text">
            <template #default="{ trigger }">
              <OnyxButton label="Center" v-bind="trigger" />
            </template>
          </OnyxTooltip>
          <OnyxTooltip text="Example tooltip text">
            <template #default="{ trigger }">
              <OnyxButton label="Center" v-bind="trigger" />
            </template>
          </OnyxTooltip>
          <OnyxTooltip text="Example tooltip text">
            <template #default="{ trigger }">
              <OnyxButton label="Right" v-bind="trigger" />
            </template>
          </OnyxTooltip>
        </div>
```

2024-09-03 07:41 UTC, MajaZarkova requested changes

2024-09-03 07:41 UTC, MajaZarkova commented on packages/sit-onyx/src/components/OnyxTooltip/OnyxTooltip.stories.ts
> +    de,
"de" is throwing an error in Storybook, it's not needed here :)

![image](https://github.com/user-attachments/assets/304b226d-6303-4c29-8742-99777d5c3901)

2024-09-03 07:41 UTC, MajaZarkova commented on packages/sit-onyx/src/components/OnyxTooltip/OnyxTooltip.stories.ts
Maybe it's better to add a separate example for top alignment, or combination with top/right, bottom/left... something like that.

2024-09-03 07:41 UTC, MajaZarkova commented on packages/sit-onyx/src/components/OnyxTooltip/types.ts
> +  float?: TooltipFloat;
```suggestion
  alignment?: TooltipFloat;
```

I think alignment is more suitable :)

2024-09-03 07:41 UTC, MajaZarkova commented on packages/sit-onyx/src/components/OnyxTooltip/types.ts
> +export const TOOLTIP_FLOAT = ["left", "right", "center", "auto"] as const;
```suggestion
export const TOOLTIP_ALIGNMENT = ["left", "right", "center", "auto"] as const;
```

2024-09-03 07:41 UTC, MajaZarkova commented on packages/sit-onyx/src/components/OnyxTooltip/types.ts
> +export type TooltipFloat = (typeof TOOLTIP_FLOAT)[number];
```suggestion
export type TooltipAlignment = (typeof TOOLTIP_ALIGNMENT)[number];
```

2024-09-03 07:41 UTC, MajaZarkova commented on packages/sit-onyx/src/components/OnyxTooltip/OnyxTooltip.vue
> +// classes for the tooltip | computed to drevent bugs
```suggestion
// classes for the tooltip | computed to prevent bugs
```

2024-09-03 07:41 UTC, MajaZarkova commented on packages/sit-onyx/src/components/OnyxTooltip/OnyxTooltip.vue
> +    ["onyx-tooltip--" + openDirection]: props.position === "auto",
```suggestion
    [`onyx-tooltip--${openDirection}`]: props.position === "auto",
```

2024-09-03 07:41 UTC, MajaZarkova commented on packages/sit-onyx/src/components/OnyxTooltip/OnyxTooltip.vue
> +    "onyx-tooltip--bottom": props.position === "bottom",
```suggestion
    [`onyx-tooltip--${props.position}`]: props.position != "auto",
```

2024-09-03 07:41 UTC, MajaZarkova commented on packages/sit-onyx/src/components/OnyxTooltip/OnyxTooltip.vue
> +    "onyx-tooltip--float--right": props.float === "right",
```suggestion
    [`onyx-tooltip--float--${props.float}`]: props.float != "auto",
```

2024-09-03 07:41 UTC, MajaZarkova commented on packages/sit-onyx/src/components/OnyxTooltip/OnyxTooltip.vue
> +    ["onyx-tooltip--float--" + wedgePosition]: wedgePosition && props.float === "auto",
```suggestion
    [`onyx-tooltip--float--${wedgePosition}`]: wedgePosition && props.float === "auto",
```

2024-09-03 07:41 UTC, MajaZarkova commented on packages/sit-onyx/src/components/OnyxTooltip/OnyxTooltip.vue
> +// update open direction on resize and to ensure the tooltip is always visible
```suggestion
// update open direction on resize to ensure the tooltip is always visible
```

2024-09-03 07:41 UTC, MajaZarkova commented on packages/sit-onyx/src/components/OnyxTooltip/OnyxTooltip.vue
> +  const updateOnEvent = () => {
```suggestion
  const updateOnResize = () => {
```

2024-09-03 07:41 UTC, MajaZarkova commented on packages/sit-onyx/src/components/OnyxTooltip/OnyxTooltip.vue
> +// update open direction on visibliity changes ensure the tooltip is always visible
```suggestion
// update open direction when visibility changes to ensure the tooltip is always visible
```

2024-09-13 14:22 UTC, larsrickert requested changes

2024-09-13 14:22 UTC, larsrickert commented on packages/sit-onyx/src/components/OnyxTooltip/OnyxTooltip.vue
> +});
```suggestion
const updateDirections = () => {
    updateOpenDirection();
    updateWedgePosition();
};
  
useGlobalEventListener({
  type: "resize",
  listener: () => updateDirections(),
});

// initial update
onMounted(() => updateDirections());
```

We have a utility from other `@sit-onyx/headless` package for this which already covers the unMounted / unmount part :)

2024-09-13 14:22 UTC, larsrickert commented on packages/sit-onyx/src/components/OnyxTooltip/OnyxTooltip.vue
> +    [`onyx-tooltip--align--${props.align}`]: props.align !== "auto",
```suggestion
    [`onyx-tooltip--${wedgePosition.value}`]: props.align === "auto",
    [`onyx-tooltip--${props.align}`]: props.align !== "auto",
```

in BEM there is only 1 `--` allowed, so we need to rename it e.g. like this

2024-09-13 14:22 UTC, larsrickert commented on packages/sit-onyx/src/composables/useWedgePosition.ts
> +  const findParentWithHiddenOverflow = (element?: Element): Element | undefined => {
This is copied from the `useOpenDirection` composable, right? So we could export it there to not duplicate code

2024-10-02 11:29 UTC, MajaZarkova requested changes

2024-10-02 11:29 UTC, MajaZarkova commented on packages/sit-onyx/playwright/snapshots/components/OnyxTooltip/Tooltip-chromium-linux.png
Maybe we should extend the width for the long text column, so that  the tooltip is not cut off

2024-10-02 15:02 UTC, ChristianBusshoff commented on packages/sit-onyx/playwright/snapshots/components/OnyxTooltip/Tooltip-chromium-linux.png
fixed it

2024-10-03 06:05 UTC, MajaZarkova commented on packages/sit-onyx/playwright/snapshots/components/OnyxTooltip/Tooltip-chromium-linux.png
You should update the screenshot tests too :)

2024-10-04 07:38 UTC, MajaZarkova submitted a review, later dismissed

2024-10-09 07:45 UTC, larsrickert requested changes

2024-10-15 10:07 UTC, larsrickert requested changes

2024-10-15 10:07 UTC, larsrickert commented on packages/sit-onyx/src/components/OnyxCheckbox/OnyxCheckbox.stories.ts
I noticed a weird behavior for the checkbox (also affects other components like thenSwitch):
If it shows the tooltip for the first time, the alignment is incorrect so the tooltip is cut off. When hovering out and then on the checkbox again, the tooltip is then shown correctly.

https://github.com/user-attachments/assets/a8d02eb3-ff08-4af1-a2db-27ddf5fa99b3

2024-10-15 10:14 UTC, ChristianBusshoff commented on packages/sit-onyx/src/components/OnyxTooltip/OnyxTooltip.stories.ts
> +    },
Without it it's an input field instead of options. Is there another way to determine this behavior?

2024-10-15 12:00 UTC, larsrickert commented on packages/sit-onyx/src/components/OnyxTooltip/OnyxTooltip.stories.ts
> +    },
Works for me 🤔  Did you restart Storybook after removing it?
<img width="588" alt="image" src="https://github.com/user-attachments/assets/2beb8c66-b9ab-459a-9e32-dcfa1f6ca4dd">

2024-10-18 08:27 UTC, ChristianBusshoff commented on packages/sit-onyx/src/components/OnyxCheckbox/OnyxCheckbox.stories.ts
I spoke with Jonathan, and he said that I should remove the CSS logic that shows the error message only after user interaction in this PR, as it will be addressed in a separate ticket later.

2024-10-18 08:28 UTC, ChristianBusshoff commented on apps/demo-app/src/views/HomeView.vue
It does but also in main. So I think it's not related to this PR

2024-10-18 08:29 UTC, ChristianBusshoff commented on packages/sit-onyx/src/components/OnyxTooltip/OnyxTooltip.stories.ts
> +    },
I restarted Storybook, now it's working also for me. So I changed it.

2024-10-18 08:29 UTC, ChristianBusshoff commented on packages/sit-onyx/src/composables/useOpenDirection.ts
> +  defaultDirection = "bottom" as OpenDirection,
I changed it.

2024-10-18 08:32 UTC, ChristianBusshoff commented on packages/sit-onyx/src/components/OnyxTooltip/OnyxTooltip.vue
> +  //TODO: fix the attribute type
the ToDo will not be addressed in this ticket

2024-10-18 10:12 UTC, larsrickert requested changes

2024-10-18 10:12 UTC, larsrickert commented on packages/sit-onyx/playwright/snapshots/components/OnyxInput/Input-labelTooltip-messageTooltip--chromium-linux.png
Imho we tooltip should open to the top if there is enough space (see screenshot).
Otherwise it overlays the input component. Same for stepper, select and texatrea :)
![image](https://github.com/user-attachments/assets/f279bd0e-8756-4254-923f-68d7d61eedee)

2024-10-24 14:25 UTC, larsrickert commented
@ChristianBusshoff  Can you add a changeset so this feature is released to the users?

2024-10-25 07:05 UTC, larsrickert approved these changes

2024-10-25 07:08 UTC, merged