add relevant events logging
SchwarzIT/onyx pull request #1880
Opened 2024-09-17 14:38 UTC by JoCa96

A new Storybook Util `withNativeEventLoggingFor` is introduced.
It generates Storybook `ArgTypes` that allow us to document and log relevant native events in Storybook.
These can be merged with other `ArgTypes`.
The native events will be documented in a new section "Relevant HTML Events".

Relates to #1603

2024-09-17 14:57 UTC, larsrickert requested changes

2024-09-17 14:57 UTC, larsrickert commented on .changeset/tender-zebras-flow.md
> +feat: added withNativeEventLogging to log and document native events
Should we also document this utility in our docs?

2024-09-17 14:57 UTC, larsrickert commented on packages/storybook-utils/src/actions.ts
> +      name: eventName,
```suggestion
      name: action,
```

Would prefer to show the event with the on prefix

2024-09-17 14:57 UTC, larsrickert commented on packages/storybook-utils/src/actions.ts
> +      description: `[${action}_event](https://developer.mozilla.org/en-US/search?q=element+${action}+event)`, // unfortunately there is no static path for all events
```suggestion
      description: `Native HTML [${action}](https://developer.mozilla.org/en-US/search?q=element+${action}+event) event`, // unfortunately there is no static path for all events
```

2024-09-17 14:57 UTC, larsrickert commented on packages/storybook-utils/src/actions.ts
> +      description: `[${action}_event](https://developer.mozilla.org/en-US/search?q=element+${action}+event)`, // unfortunately there is no static path for all events
(optional) we could maintain a map of "real" links for very common events like click, change, focus etc. and use the generic search link for all other events, what do you think?

If its too much manual maintenance we don't have to do it :)

2024-09-18 09:20 UTC, JoCa96 commented on packages/storybook-utils/src/actions.ts
> +      description: `[${action}_event](https://developer.mozilla.org/en-US/search?q=element+${action}+event)`, // unfortunately there is no static path for all events
Done, I had some fun with typescript :D

2024-09-18 09:51 UTC, larsrickert requested changes
👏

2024-09-18 09:51 UTC, larsrickert commented on packages/storybook-utils/src/events.ts
> +> = TString extends `${Prefix}${infer Base}` ? Base : TString;
```suggestion
  TPrefix extends string,
> = TString extends `${TPrefix}${infer TBase}` ? TBase : TString;
```

Isn't it a convention to prefix generic types with T?

2024-09-18 09:51 UTC, larsrickert commented on packages/storybook-utils/src/events.ts
> +export const EVENT_DOC_MAP: EventDocMap = {
Nice TypeScript magic :D
Couldn't we map the event.name from the key? If I see correctly, the EVENT_DOC_MAP is always the event.name with the `on` prefix

2024-09-18 10:43 UTC, larsrickert commented on packages/storybook-utils/src/events.ts
> +export const EVENT_DOC_MAP: EventDocMap = {
I meant the keys from our own `EVENT_DOC_MAP` :) So when we use it in the Storybook util, we could extract the event name from the key so we don't need to maintain them manually

2024-09-18 10:56 UTC, larsrickert approved these changes

2024-09-18 11:27 UTC, merged