Use Edge browser for Onyx Playwright tests
SchwarzIT/onyx pull request #2130
Opened 2024-11-20 15:41 UTC by oemueller

Relates to #1997

Use MS Edge in Playwright tests for Onyx, since this is the most important browser.
(Also Chromium based but the version is a few weeks older and has possible other minor differences) 
https://playwright.dev/docs/browsers#configure-browsers

## Checklist

- [ ] A changeset is added with `npx changeset add` if your changes should be released as npm package (because they affect the library usage)

2024-11-22 06:45 UTC, larsrickert requested changes

2024-11-22 06:45 UTC, larsrickert commented on packages/sit-onyx/playwright.config.ts
> +    { name: "Microsoft Edge", use: { ...devices["Desktop Edge"], channel: "msedge" } },
```suggestion
    { name: "edge", use: { ...devices["Desktop Edge"], channel: "msedge" } },
```

For the other browsers is also just the browser name and lowercase :) This name will be added to the screenshot names so I would keep it short here

2024-11-25 15:17 UTC, larsrickert submitted a review, later dismissed

2024-11-25 15:17 UTC, larsrickert commented on .changeset/empty-drinks-sniff.md
We can omit the changeset since this is an internal only change that does not require a new npm package version to be released to our users :)

2024-11-25 15:18 UTC, larsrickert commented
> Shall we use Edge in other packages as well ?

@oemueller Sure why not so its the same for all packages :)

2024-11-28 08:20 UTC, oemueller commented
@JoCa96 can you approve ? all issues resolved :-)

2024-11-28 10:29 UTC, JoCa96 commented on apps/docs/playwright/snapshots/about-team-chromium-linux.png
Where are the new screenshots that replace these?

2024-11-28 16:14 UTC, oemueller commented on apps/docs/playwright/snapshots/about-team-chromium-linux.png
there was a problem with the test file pattern in docs app so no tests where found. I changed it to: ` `**/*.ct.{ts,tsx}``

2024-11-28 18:10 UTC, JoCa96 approved these changes

2024-11-28 18:11 UTC, JoCa96 commented
Approved :)

2024-12-03 09:46 UTC, merged