change where(.dark) to .dark
SchwarzIT/onyx pull request #2211
Opened 2024-12-03 07:34 UTC by ChristianBusshoff

Relates to #

## Checklist

- [ ] The added / edited code has been documented with [JSDoc](https://jsdoc.app/about-getting-started)
- [ ] All changes are documented in the documentation app (folder `apps/docs`)
- [ ] If a new component is added, at least one [Playwright screenshot test](https://github.com/SchwarzIT/onyx/actions/workflows/playwright-screenshots.yml) is added
- [ ] A changeset is added with `npx changeset add` if your changes should be released as npm package (because they affect the library usage)

2024-12-03 07:38 UTC, JoCa96 commented
Please update the description

2024-12-03 07:57 UTC, larsrickert approved these changes

2024-12-03 07:57 UTC, larsrickert requested changes
Can you please add a changeset so this change is released?

2024-12-05 08:55 UTC, larsrickert approved these changes

2024-12-05 09:14 UTC, merged