feat: implement linting tests
SchwarzIT/onyx pull request #2333
Opened 2024-12-13 09:30 UTC by ChristianBusshoff

- created linting tests for the following rules:
 - import-playwright-a11y.cjs
 - no-shadow-native-events.cjs
 - require-root-class

- removed unnessesary testing from require-root-class because it's already tested on default.

2024-12-16 15:56 UTC, JoCa96 requested changes

2024-12-18 12:52 UTC, ChristianBusshoff commented on package.json
> +    "test:eslint-plugins": " node ./packages/eslint-plugin/src/tests/index.cjs ",
moved it

2024-12-18 14:06 UTC, JoCa96 approved these changes

2024-12-18 14:18 UTC, JoCa96 requested changes
Please ensure that, the tests are run in the check.yaml pipeline

2024-12-18 14:19 UTC, JoCa96 approved these changes
Please ensure that, the tests are run in the check.yaml pipeline or create a follow-up ticket.

2024-12-19 07:54 UTC, merged