feat(docs): Implement new component overview
SchwarzIT/onyx pull request #2339
Opened 2024-12-16 09:04 UTC by MajaZarkova

Relates to #2298 

- Remove due indicator
- Replace icon buttons with icons
- Use new icons

## Checklist

- [x] All changes are documented in the documentation app (folder `apps/docs`)

2024-12-16 14:09 UTC, larsrickert requested changes

2024-12-16 14:09 UTC, larsrickert commented on apps/docs/src/.vitepress/components/ComponentRoadmap.vue
> +  return sortedComponents.value.slice(0, showAll.value ? undefined : 16);
Can we change the default value of `showAll` to `true` so the user sees all components initially and can then clic to show less? I already talked with Martin about this and its okay for him

2024-12-16 14:09 UTC, larsrickert commented on apps/docs/src/index.data.ts
Did you check the components and their statuses with the ones mentioned in #2298?
Also the data grid exists twice :)

2024-12-16 16:01 UTC, larsrickert requested changes

2024-12-16 16:01 UTC, larsrickert commented on apps/docs/src/index.data.ts
I discussed a few status changes with Martin:
- mark button and toast as "implemented"
- add "Notification center" as "planned"

I also updated the ticket

2024-12-17 07:25 UTC, MajaZarkova commented on apps/docs/src/index.data.ts
> +        status: "in-progress",
@larsrickert  According to the ticket some of the components does not have a storybook file yet, but are market 'in-progress'. Maybe we can discuss this on the dev exchange.

2024-12-17 13:35 UTC, merged