feat(OnyxBottomBar): Implement OnyxBottomBar
SchwarzIT/onyx pull request #2382
Opened 2024-12-19 13:47 UTC by MajaZarkova

Relates to #2290 

Implement OnyxBottomBar component

## Checklist

- [x] The added / edited code has been documented with [JSDoc](https://jsdoc.app/about-getting-started)
- [ ] All changes are documented in the documentation app (folder `apps/docs`)
- [ ] If a new component is added, at least one [Playwright screenshot test](https://github.com/SchwarzIT/onyx/actions/workflows/playwright-screenshots.yml) is added
- [x] A changeset is added with `npx changeset add` if your changes should be released as npm package (because they affect the library usage)

2024-12-19 14:47 UTC, larsrickert requested changes

2024-12-19 14:47 UTC, larsrickert commented on packages/sit-onyx/src/components/OnyxBottomBar/OnyxBottomBar.vue
> +      { 'onyx-bottom-bar--border': !props.hideTopBorder },
```suggestion
      props.hideTopBorder ? '' : 'onyx-bottom-bar--border',
```

2024-12-19 14:47 UTC, larsrickert commented on packages/sit-onyx/src/components/OnyxBottomBar/OnyxBottomBar.vue
> +      gap: 0.5rem;
```suggestion
    gap: var(--onyx-density-xs);
    padding: var(--onyx-spacing-2xs) var(--onyx-grid-margin);
    overflow-x: auto;

    &--border {
      border-top: var(--onyx-1px-in-rem) solid var(--onyx-color-component-border-neutral);
    }

    &__left,
    &__right {
      position: relative;
      display: flex;
      width: max-content;
      gap: var(--onyx-density-xs);
```

Figma uses `--onyx-density-xs` for the gap :)

2024-12-19 14:47 UTC, larsrickert commented on packages/sit-onyx/src/components/OnyxBottomBar/OnyxBottomBar.vue
> +    width: var(--onyx-grid-margin-inline, 100%);
```suggestion
    margin-inline: var(--onyx-grid-margin-inline);
```

onyx-grid-margin-inline is responsible for centering so we should use `margin-inline` instead :)

2024-12-19 14:47 UTC, larsrickert commented on packages/sit-onyx/src/components/OnyxBottomBar/OnyxBottomBar.vue
> +    max-width: var(--onyx-grid-max-width, 100%);
The parent div should be full width so the border uses the full width. Only the content of the bottom bar should consider the max width

2024-12-19 14:47 UTC, larsrickert commented on packages/sit-onyx/src/components/OnyxBottomBar/types.ts
> +  hideTopBorder?: boolean;
Since we only have one border we could also name it `hideBorder` so its shorter :D

2024-12-19 14:47 UTC, larsrickert commented on packages/sit-onyx/src/components/OnyxBottomBar/OnyxBottomBar.vue
We also need to export the component in the `src/index.ts`, otherwise its not usable by the user

2024-12-19 14:47 UTC, larsrickert commented on packages/sit-onyx/src/components/OnyxBottomBar/OnyxBottomBar.stories.ts
> +export const WithRightSlot = {
Would prefer to rename it to "Default"

2024-12-19 14:47 UTC, larsrickert commented on packages/sit-onyx/src/components/OnyxBottomBar/OnyxBottomBar.stories.ts
> +    right: () => [h(OnyxButton, { label: "OK" }), h(OnyxButton, { label: "Cancel" })],
Can we align the button examples with Figma? :)

2024-12-19 14:47 UTC, larsrickert commented on packages/sit-onyx/src/components/OnyxBottomBar/OnyxBottomBar.stories.ts
> + * A bottom bar is a navigation bar at the bottom of an app or webpage.
Please also mention the page layout here :) Ideally with a link to it

2024-12-20 11:48 UTC, JoCa96 approved these changes

2024-12-20 11:59 UTC, merged