Feat/2140 implement onyx accordion component
SchwarzIT/onyx pull request #2401
Opened 2024-12-23 07:44 UTC by ChristianBusshoff

- implement OnyxAccordion & AccordionItem

2025-01-02 10:32 UTC, larsrickert requested changes

2025-01-02 10:32 UTC, larsrickert commented on packages/sit-onyx/src/components/OnyxAccordionItem/OnyxAccordionItem.vue
> +<style lang="scss">
Could you please check the styles with Figma? There are currently a few differences like text color, font weight etc.

Also, I'd prefer to use a flex layout instead of positioning the chevron icon absolute

2025-01-07 13:18 UTC, larsrickert requested changes

2025-01-07 13:18 UTC, larsrickert commented on packages/sit-onyx/src/components/OnyxAccordionItem/types.ts
> +export type OnyxAccordionItemProps = DensityProp & {
Would be nice if the open state can be controlled as prop so you could e.g. open it programatically or set it open initially on page load.

You don't have to do it in this PR

2025-01-07 13:18 UTC, larsrickert commented on packages/sit-onyx/src/components/OnyxAccordionItem/OnyxAccordionItem.vue
> +      :tabindex="accordionContext?.disabled.value || props.disabled ? -1 : 0"
We have this disabled logic with `||` multiple times in this file, maybe you could create a `isDisabled` computed that unifies this

2025-01-07 13:18 UTC, larsrickert commented on packages/sit-onyx/src/components/OnyxAccordionItem/OnyxAccordionItem.vue
> +      <div class="onyx-accordion-item__header__content">
In BEM naming only one `__` can be used so we would need to rename this, e.g. to `onyx-accordion-item__header-content`

2025-01-07 13:18 UTC, larsrickert commented on packages/sit-onyx/src/components/OnyxAccordionItem/OnyxAccordionItem.vue
> +      <div class="onyx-accordion-item__header__content">
Same for `__header__icon`

2025-01-07 13:18 UTC, larsrickert commented on packages/sit-onyx/src/components/OnyxAccordionItem/OnyxAccordionItem.vue
> +        label="toggle-accordion-icon"
```suggestion
```

The icon does not have a label prop

2025-01-07 13:18 UTC, larsrickert commented on packages/sit-onyx/src/components/OnyxAccordionItem/OnyxAccordionItem.vue
> +    overflow: hidden;
Why is this needed? This would cut off things like tooltips or flyouts

2025-01-08 07:44 UTC, larsrickert requested changes

2025-01-08 07:44 UTC, larsrickert commented on packages/sit-onyx/src/components/OnyxAccordion/OnyxAccordion.ct.tsx
> +  const secondPanel = component.locator(".onyx-accordion-item__panel").nth(1);
```suggestion
  const firstHeader = component.getByRole('button', { name: 'Accordion Header 1' });
  const secondHeader = component.getByRole('button', { name: 'Accordion Header 2' });
  const firstPanel = component.getByLabel('Accordion Header 1');
  const secondPanel = component.getByLabel('Accordion Header 2');
```

We should try to avoid using `.locator()` and instead using Playwright web native selectors like `getByRole()` or `getByLabel()`.

You can use the VS Code Playwright extension to just click on elements and it will copy the selector :)

<img width="196" alt="image" src="https://github.com/user-attachments/assets/fdf058d9-3d4d-413c-b4f5-e2f5d203ab20" />

![image](https://github.com/user-attachments/assets/092001ca-4a62-4f74-974c-fcae4bbce2c7)

2025-01-08 07:44 UTC, larsrickert commented on packages/sit-onyx/src/components/OnyxAccordion/OnyxAccordion.ct.tsx
You still need to run the Playwright screenshot pipeline to generate the screenshots :)

2025-01-08 07:44 UTC, larsrickert commented on packages/sit-onyx/src/components/OnyxAccordion/OnyxAccordion.ct.tsx
> +  const secondPanel = component.locator(".onyx-accordion-item__panel").nth(1);
Same for the OnyxAccordionItem tests

2025-01-08 07:44 UTC, larsrickert commented on packages/sit-onyx/src/components/OnyxAccordionItem/OnyxAccordionItem.vue
> +const isDiabled = computed(() => accordionContext?.disabled.value || props.disabled);
```suggestion
const isDisabled = computed(() => accordionContext?.disabled.value || props.disabled);
```

2025-01-08 07:44 UTC, larsrickert commented on packages/sit-onyx/src/components/OnyxAccordionItem/OnyxAccordionItem.vue
> +        * {
Hmm not sure if we should apply `*` here...this was to change the font styles when e.g. `<h3>` is used, right? Maybe we should just remove the usage of h3 instead and use plain text for the header

2025-01-08 07:44 UTC, larsrickert commented on packages/sit-onyx/src/components/OnyxAccordionItem/OnyxAccordionItem.vue
> +        * {
@JoCa96 What do you think?

2025-01-08 07:44 UTC, larsrickert commented on packages/sit-onyx/src/components/OnyxAccordionItem/OnyxAccordionItem.vue
> +      cursor: pointer;
Cursor is not applied for me

2025-01-08 07:44 UTC, larsrickert commented on packages/sit-onyx/src/components/OnyxAccordionItem/OnyxAccordionItem.vue
> +    &:has(:focus-visible) {
```suggestion
    &:has(&__header:focus-visible) {
```

Otherwise it would apply to any focus-visible elements, e.g. inputs inside the panel which is not intended I guess

2025-01-08 07:44 UTC, larsrickert commented on packages/sit-onyx/src/components/OnyxAccordionItem/OnyxAccordionItem.vue
> +      z-index: 1;
Why is the z-index needed?

2025-01-08 07:44 UTC, larsrickert commented on packages/sit-onyx/src/components/OnyxAccordionItem/OnyxAccordionItem.vue
> +      border-radius: var(--onyx-radius-md);
border radius does not seem to be applied
![image](https://github.com/user-attachments/assets/f6f7e49f-a1fe-4feb-9781-238126f2fd32)

2025-01-08 07:44 UTC, larsrickert commented on packages/sit-onyx/src/components/OnyxAccordionItem/OnyxAccordionItem.vue
> +      color: var(--onyx-color-text-icons-neutral-soft);
This would also change the text color of the panel, is this intended?

2025-01-08 07:44 UTC, larsrickert commented on packages/sit-onyx/src/components/OnyxAccordionItem/OnyxAccordionItem.vue
> +    border-bottom: 1px solid var(--onyx-color-component-border-neutral);
```suggestion
    border-bottom: var(--onyx-1px-in-rem) solid var(--onyx-color-component-border-neutral);
```

2025-01-08 07:44 UTC, larsrickert commented on packages/sit-onyx/src/components/OnyxAccordionItem/OnyxAccordionItem.vue
> +      width: calc(100% - 3 * var(--onyx-density-md));
Thats the same as `var(--onyx-density-2xl)`. Is there a reason why you are calculating here? Does it depend on some other styles, e.g. the padding value?

2025-01-08 07:44 UTC, larsrickert commented on packages/sit-onyx/src/components/OnyxAccordionItem/OnyxAccordionItem.vue
> +      height: var(--onyx-density-md);
If I see it correctly in Figma, the icon always has the same size for all densities. Only the padding changes

2025-01-08 07:44 UTC, larsrickert commented on packages/sit-onyx/src/components/OnyxAccordionItem/OnyxAccordionItem.vue
> +      height: var(--onyx-density-md);
Same for the main element height

2025-01-09 08:07 UTC, ChristianBusshoff commented on packages/sit-onyx/src/components/OnyxAccordionItem/OnyxAccordionItem.vue
> +      color: var(--onyx-color-text-icons-neutral-soft);
yes, cause open panels can also be disabled

2025-01-09 08:11 UTC, ChristianBusshoff commented on packages/sit-onyx/src/components/OnyxAccordionItem/OnyxAccordionItem.vue
> +      width: calc(100% - 3 * var(--onyx-density-md));
it's 3 times the padding value

2025-01-09 08:20 UTC, larsrickert commented on packages/sit-onyx/src/components/OnyxAccordionItem/OnyxAccordionItem.vue
> +      width: calc(100% - 3 * var(--onyx-density-md));
Then please add a new custom CSS variable like `--onyx-accordion-padding` and use this one so it behaves as expected when we change the padding in the future :)

2025-01-14 15:11 UTC, larsrickert requested changes

2025-01-15 06:26 UTC, larsrickert approved these changes

2025-01-15 13:26 UTC, merged