docs(icons): Implement search functionality in icon library
SchwarzIT/onyx pull request #263
Opened 2024-02-08 14:41 UTC by BoppLi

Part of #424

Implements a search functionality for our icon library documentation.

<img width="470" alt="image" src="https://github.com/SchwarzIT/onyx/assets/151019977/394379ad-7af6-4fa6-8ab9-8ad958e8e8d1">

## Checklist

- [ ] The added / edited code has been documented with [JSDoc](https://jsdoc.app/about-getting-started)
- [ ] All changes are documented in the documentation app (folder `apps/docs`)
- [ ] If a new component is added, at least one [Playwright screenshot test](https://github.com/SchwarzIT/onyx/actions/workflows/playwright-screenshots.yml) is added
- [ ] A changeset is added with `npx changeset add` if your changes should be released as npm package (because they affect the library usage)

2024-02-08 14:45 UTC, BoppLi commented on apps/docs/src/.vitepress/utils-icons.ts
> +  const importName = parts
info: the importName is not used yet, it will be used in the copy functionality which will be added in the next PR.

2024-02-08 14:50 UTC, JoCa96 requested changes

2024-02-08 14:50 UTC, JoCa96 commented on apps/docs/src/.vitepress/utils-icons.ts
> +const getIconContextData = (iconName: string, ALL_ICONS: Record<string, string>) => {
Please rename `ALL_ICONS` parameter as it is not a global constant in this context:
```suggestion
const getIconContextData = (iconName: string, allIcons: Record<string, string>) => {
```

2024-02-08 14:50 UTC, JoCa96 commented on apps/docs/src/.vitepress/utils-icons.ts
> +export const getEnrichedIconCategoryList = (ALL_ICONS: Record<string, string>) =>
same as above

2024-02-08 14:50 UTC, JoCa96 commented on apps/docs/src/.vitepress/components/Search.vue
> +  padding: var(--onyx-spacing-2xs, 8px);
please use rem

2024-02-09 07:57 UTC, JoCa96 approved these changes

2024-02-09 08:02 UTC, merged