Fix disabled button state
SchwarzIT/onyx pull request #397
Opened 2024-02-22 09:31 UTC by MajaZarkova

closes #384 

Removed the hover effect when the button is disabled. I also adjusted the correct height of the button.

## Checklist

- [ ] The added / edited code has been documented with [JSDoc](https://jsdoc.app/about-getting-started)
- [ ] All changes are documented in the documentation app (folder `apps/docs`)
- [ ] If a new component is added, at least one [Playwright screenshot test](https://github.com/SchwarzIT/onyx/actions/workflows/playwright-screenshots.yml) is added
- [ ] A changeset is added with `npx changeset add` if your changes should be released as npm package (because they affect the library usage)

2024-02-22 10:39 UTC, JoCa96 requested changes

2024-02-22 10:39 UTC, JoCa96 commented on packages/sit-onyx/src/components/OnyxButton/OnyxButton.vue
> +    pointer-events: none;
We must avoid `pointer-events: none;` as it introduces other side effects.
Instead, you could only apply the `:hover` when the button is also `:enabled`

2024-02-22 10:39 UTC, JoCa96 commented on packages/sit-onyx/src/components/OnyxButton/OnyxButton.vue
> +  height: 2.5rem;
You also need `box-sizing: border-box` for this to have the correct height :)

2024-02-22 12:14 UTC, JoCa96 approved these changes

2024-02-23 07:31 UTC, jannick-ux approved these changes

2024-02-23 07:35 UTC, merged