chore: Update PR template
SchwarzIT/onyx pull request #400
Opened 2024-02-22 14:09 UTC by MajaZarkova

Replace "closes" with "relates to"

## Checklist

- [X] The added / edited code has been documented with [JSDoc](https://jsdoc.app/about-getting-started)
- [X] All changes are documented in the documentation app (folder `apps/docs`)
- [X] If a new component is added, at least one [Playwright screenshot test](https://github.com/SchwarzIT/onyx/actions/workflows/playwright-screenshots.yml) is added
- [X] A changeset is added with `npx changeset add` if your changes should be released as npm package (because they affect the library usage)

2024-02-22 14:23 UTC, BoppLi commented on .changeset/great-sloths-fetch.md
> +Update PR template
no changeset for this PR pls because for the user of onyx nothing changes :)

2024-02-22 14:24 UTC, BoppLi requested changes

2024-02-22 14:24 UTC, BoppLi commented on .changeset/great-sloths-fetch.md
> +Update PR template
no changeset for this PR pls because for the user of onyx nothing changes :)

2024-02-22 14:25 UTC, BoppLi commented on .changeset/great-sloths-fetch.md
> +Update PR template
see pr template text:
> if your changes should be released as npm package (because they affect the library usage)

2024-02-23 08:09 UTC, JoCa96 approved these changes

2024-02-23 08:38 UTC, BoppLi approved these changes

2024-02-23 09:16 UTC, merged