feat: add OnyxLoading indicator
SchwarzIT/onyx pull request #418
Opened 2024-02-26 12:05 UTC by larsrickert

relates to #390

Implement the "circle" type of the OnyxLoadingIndicator.
The `type="dots"` will be animated in a follow up PR.

## Checklist

- [x] The added / edited code has been documented with [JSDoc](https://jsdoc.app/about-getting-started)
- [x] A changeset is added with `npx changeset add` if your changes should be released as npm package (because they affect the library usage)

2024-02-26 14:00 UTC, JoCa96 requested changes

2024-02-26 14:00 UTC, JoCa96 commented on packages/sit-onyx/src/styles/index.scss
> +  --onyx-duration-lg: 1s;
Where did you get these timings from?

2024-02-26 14:22 UTC, larsrickert commented on packages/sit-onyx/src/styles/index.scss
> +    --onyx-duration-sm: 0;
Since the animation are infinite, using 1ms will lead to a insanely fast animation, we would need to use some very high value like `999s`

2024-02-27 09:56 UTC, JoCa96 commented on packages/sit-onyx/src/styles/index.scss
> +    --onyx-duration-sm: 0;
What about setting `[animation-iteration-count](https://developer.mozilla.org/en-US/docs/Web/CSS/animation-iteration-count)` to `1`?

2024-02-27 10:01 UTC, larsrickert commented on packages/sit-onyx/src/styles/index.scss
> +    --onyx-duration-sm: 0;
For infinite animations I would just set `animation: none` since it does not make sense to listen to `transitionstart` or `transitionend` event there

2024-02-27 10:08 UTC, BoppLi commented on packages/sit-onyx/src/styles/index.scss
> +    --onyx-duration-sm: 0;
remember, there is a [follow up ticket](https://github.com/orgs/SchwarzIT/projects/5/views/7?filterQuery=reduce&pane=issue&itemId=53992786) so it does not have to be solved in this PR :)

2024-02-27 11:52 UTC, JoCa96 commented on packages/sit-onyx/src/styles/index.scss
> +    --onyx-duration-sm: 0;
@larsrickert Then you will need to start differentiating between infinite and finite animations

2024-02-27 15:41 UTC, larsrickert commented on packages/sit-onyx/src/styles/index.scss
> +    --onyx-duration-sm: 0;
Hmm...I removed prefers-reduced-motion for now so this PR can be merged.
Lets discuss how to handle it in #428

2024-02-28 08:49 UTC, BoppLi submitted a review, later dismissed

2024-02-28 09:52 UTC, BoppLi approved these changes

2024-02-28 09:54 UTC, merged