docs: setup Storybook for custom VitePress components
SchwarzIT/onyx pull request #434
Opened 2024-02-27 17:03 UTC by larsrickert

Setup Storybook for our custom VitePress components so its easier to develop them and to see which custom components we have.

Note: For some components we can not create a `.stories.ts` file because they import some VitePress or node specific things which do not work in Storybook.

2024-02-28 17:23 UTC, JoCa96 commented
@BoppLi Can you review this please?

2024-03-01 13:10 UTC, BoppLi requested changes
8/26

2024-03-01 13:10 UTC, BoppLi commented on apps/docs/src/.vitepress/components/DesignTokenHeader.vue
> +    <OnyxHeadline is="h3">{{ props.headline }}</OnyxHeadline>
<img width="354" alt="image" src="https://github.com/SchwarzIT/onyx/assets/151019977/6fda1442-b5ea-4445-ad6c-0d921c2130fd">

vitepress sets a margin on h3 headline. please unset the headline margin here.

2024-03-01 13:25 UTC, larsrickert commented on apps/docs/src/.vitepress/components/ColorPalette.stories.ts
> +  title: "components/ColorPalette",
Good idea! I changed it, what do you think?

2024-03-01 13:46 UTC, BoppLi requested changes
20/26 files reviewed

2024-03-01 13:46 UTC, BoppLi commented on apps/docs/src/.vitepress/components/OnyxIconLibrary.vue
> +      <OnyxHeadline is="h3" class="category__headline">{{ category.name }}</OnyxHeadline>
they now are smaller: 20px is deployed, this here makes it be 16px font-size.
I asked Jannick which is correct

2024-03-01 13:46 UTC, BoppLi commented on apps/docs/src/.vitepress/components/OnyxTypography.stories.ts
> +export const Links = {
<img width="369" alt="image" src="https://github.com/SchwarzIT/onyx/assets/151019977/293a8ba4-7b6d-4d07-88fc-8be4478c6edc">


the link example does not look right :O

2024-03-01 13:48 UTC, BoppLi commented on apps/docs/src/.vitepress/components/ColorPalette.stories.ts
> +  title: "components/ColorPalette",
I love it! 😊
maybe one adjustment: instead of "icons", "Icon Library"? else the search looks weird in there :D

2024-03-01 13:49 UTC, BoppLi commented on apps/docs/src/.vitepress/components/OnyxTypography.stories.ts
> +export const Links = {
solved with the latest state

2024-03-01 13:51 UTC, BoppLi submitted a review, later dismissed

2024-03-01 13:52 UTC, BoppLi commented on apps/docs/src/.vitepress/components/OnyxIconLibrary.vue
> +      <OnyxHeadline is="h3" class="category__headline">{{ category.name }}</OnyxHeadline>
https://www.figma.com/file/YfEUBOHk4J4nYrk04geswG/onyx---Design-System-Figma-Library?node-id=1288%3A31098&mode=dev

2024-03-01 13:52 UTC, BoppLi commented on apps/docs/src/.vitepress/components/OnyxIconLibrary.vue
> +      <OnyxHeadline is="h3" class="category__headline">{{ category.name }}</OnyxHeadline>
16px/1rem is correct :)

2024-03-01 14:15 UTC, BoppLi approved these changes

2024-03-01 15:34 UTC, merged