Refactor/46 npm scripts
SchwarzIT/onyx pull request #78
Opened 2024-01-08 13:49 UTC by larsrickert

closes #46 

- unify names of all npm scripts
- run playwright component tests in parallel job during CI for improved workflow speed

2024-01-09 13:11 UTC, JoCa96 requested changes

2024-01-09 15:56 UTC, larsrickert commented on package.json
> +    "test:unit:coverage:all": "pnpm -r --if-present test:unit:coverage",
I renamed it to `test` and `test:coverage` but I think it still makes sense to run the Playwright component tests separately in a parallel pipeline job for improved performance / speed

2024-01-12 15:39 UTC, JoCa96 approved these changes

2024-01-12 16:40 UTC, JoCa96 approved these changes

2024-01-12 16:40 UTC, merged