feat(alpha-test-app, OnyxSelect): Update alpha-test-app and OnyxSelect
SchwarzIT/onyx pull request #831
Opened 2024-04-08 14:07 UTC by MajaZarkova

Relates to #568 

Added OnyxBadge example in the alpha-test-app and replaced the temporary Badge styles with OnyxBadge in the OnyxSelect component.

## Checklist

- [x] The added / edited code has been documented with [JSDoc](https://jsdoc.app/about-getting-started)
- [x] All changes are documented in the documentation app (folder `apps/docs`)

2024-04-08 14:29 UTC, BoppLi requested changes

2024-04-08 14:29 UTC, BoppLi commented on packages/sit-onyx/src/components/OnyxSelect/OnyxSelect.vue
> +    display: flex;
I'd suggest block
```suggestion
    display: block;
    cursor: pointer;
```
here as we don't flex anything :)

2024-04-08 14:29 UTC, BoppLi commented on packages/sit-onyx/src/components/OnyxSelect/OnyxSelect.vue
> +          <OnyxBadge class="onyx-select__badge" variation="neutral">{{
I added it as suggestion :)

2024-04-08 14:30 UTC, BoppLi commented on packages/sit-onyx/src/components/OnyxSelect/OnyxSelect.vue
> +          <OnyxBadge class="onyx-select__badge" variation="neutral">{{
I added it as suggestion below :)

2024-04-08 14:36 UTC, MajaZarkova commented on packages/sit-onyx/src/components/OnyxSelect/OnyxSelect.vue
> +          <OnyxBadge class="onyx-select__badge" variation="neutral">{{
Sure :)

2024-04-09 07:57 UTC, BoppLi approved these changes

2024-04-09 07:57 UTC, merged