Fix/503 repair switch zoom alignment
SchwarzIT/onyx pull request #847
Opened 2024-04-10 06:53 UTC by BoppLi

Relates to #503

Fix the alignment of the icon in the switch when zooming with the browser

## Checklist

- [x] The added / edited code has been documented with [JSDoc](https://jsdoc.app/about-getting-started)
- [ ] If a new component is added, at least one [Playwright screenshot test](https://github.com/SchwarzIT/onyx/actions/workflows/playwright-screenshots.yml) is added
- [x] A changeset is added with `npx changeset add` if your changes should be released as npm package (because they affect the library usage)

2024-04-10 11:02 UTC, larsrickert requested changes

2024-04-10 11:02 UTC, larsrickert commented on packages/sit-onyx/src/components/OnyxSwitch/OnyxSwitch.vue
> +    // border: var(--onyx-1px-in-rem) solid transparent;
Remove uncommented code :)

2024-04-10 13:45 UTC, BoppLi commented on packages/sit-onyx/src/components/OnyxSwitch/OnyxSwitch.vue
> +    // border: var(--onyx-1px-in-rem) solid transparent;
```suggestion
```

2024-04-11 06:35 UTC, larsrickert submitted a review, later dismissed

2024-04-11 09:27 UTC, larsrickert approved these changes

2024-04-11 09:30 UTC, merged