feat(OnyxAvatar): add default slot to allow for custom content
SchwarzIT/onyx pull request #998
Opened 2024-04-22 15:45 UTC by larsrickert

Relates to https://github.com/SchwarzIT/onyx/issues/947#issuecomment-2069601749

- support custom text for OnyxAvatar
- add OnyxAvatarStack example for "+42"
- update font size for "96px" avatar size to match with Figma

## Checklist

- [x] The added / edited code has been documented with [JSDoc](https://jsdoc.app/about-getting-started)
- [x] If a new component is added, at least one [Playwright screenshot test](https://github.com/SchwarzIT/onyx/actions/workflows/playwright-screenshots.yml) is added
- [x] A changeset is added with `npx changeset add` if your changes should be released as npm package (because they affect the library usage)

2024-04-23 06:02 UTC, BoppLi requested changes

2024-04-23 06:42 UTC, larsrickert commented on packages/sit-onyx/src/components/OnyxAvatar/OnyxAvatar.ct.tsx
> -  await expect(component).toContainText("A");
Ups :) Thanks!

2024-04-23 06:43 UTC, larsrickert commented on packages/sit-onyx/playwright/snapshots/components/OnyxAvatar/Avatar-custom-content--webkit-linux.png
Yes I discussed this with Jannick. In Figma, I don't see any padding

2024-04-23 11:07 UTC, BoppLi approved these changes

2024-04-24 06:03 UTC, BoppLi approved these changes

2024-04-24 06:55 UTC, merged